.\" $Id: otl2draft.1 139 2008-04-28 06:31:00Z tbourke $
.\"
.Dd April 28, 2008
.Dt OTL2DRAFT 1
.Sh NAME
.Nm otl2draft
.Nd Convert VIM outline files into LaTeX
.Sh SYNOPSIS
.Nm
.Op Fl hvfpc
.Op Em level
.Op Fl i Ar file
.Op Fl o Ar file
.Nm
.Op Fl hvfpc
.Op Em level
.Op Ar input
.Op Ar output
.\"
.Sh DESCRIPTION
.Nm
converts the otl files used by The Vim Outliner (TVO) into LaTeX markup.
It is intended for turning outlines into draft documents, rather than into
presentations (in contrast to otl2latex).
.Pp
Lists are classed based on their first bullet.
A dash gives an enumerated list in the output, and an asterisk an itemized
list.
.Pp
Levels below subsubsection are translated into nested description lists.
.Pp
Warnings are given for badly structured otl files.
.Sh OPTIONS
.Bl -tag -width indent
.It Fl h, Fl -help
Display help for command-line options.
.It Fl v, Fl -version
Show the version number.
.It Fl f, Fl -foldmarks
Add comments for vim folding.
.It Fl p, Fl -prelude
Add a basic preamble and document environment.
.It Fl c, Fl -convert
Convert special LaTeX characters
.Pq Li \e # $ % ^ & _ { } ~
for display rather than effect.
.It Em level
Choose the LaTeX section depth for the highest level:
.br
.Fl -part ,
.Fl -chapter ,
.Fl -section
.Pq -default ,
.Fl -subsection ,
.Fl -subsubsection .
.El
.Sh EXAMPLES
Convert an outline file into a complete LaTeX document:
.Dl otl2draft -pc README.otl README.tex
.Pp
Convert an outline file for inclusion in an existing LaTeX document:
.Dl otl2draft -c --subsection sketch.otl sketch.tex
.\"
.Sh SEE ALSO
The Vim Outline website:
.Li http://bike-nomad.com/vim/vimoutliner.html
.\"
.Sh AUTHORS
.An Timothy Bourke Aq timbob@bigpond.com
